spring.profiles: test

spring:

  datasource:
    url: jdbc:h2:file:~/test_db

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true

---
spring.profiles: dev

---
spring.profiles: prod
