spring:
  profiles:
    active: test

---
spring.profiles.include:
  - service

---
spring:
  profiles: test

server:
  port: 9002

---
spring:
  profiles: dev

server:
  port: 9001

---
spring:
  profiles: prod

server:
  port: 9000
